export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SET_VACATIONS_SUCCESS = "SET_VACATIONS_SUCCESS";
export const SET_VACATIONS_FAIL = "SET_VACATIONS_FAIL";

export const FOLLOW_VACATION = "FOLLOW_VACATION";
export const UNFOLLOW_VACATION = "UNFOLLOW_VACATION";

export const ADD_VACATION = "ADD_VACATION";
export const EDIT_VACATION = "EDIT_VACATION";
export const DELETE_VACATION = "DELETE_VACATION";

export const SET_FOLLOWERS = "SET_FOLLOWERS";
